//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_NET_LAB3_GIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string TotalValue { get; set; }
        public string Date { get; set; }
        public int CustomerCustomerId1 { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
